version: '2'
services:
  api:
    container_name: satellite_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'db'
    volumes:
      - /var/lib/satellitedb
